package Vista;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVenta = new javax.swing.JMenu();
        jMenuVender = new javax.swing.JMenuItem();
        jMenuMantenimiento = new javax.swing.JMenu();
        jMenuMantenimientoVendedor = new javax.swing.JMenuItem();
        jMenuMantenimientoProducto = new javax.swing.JMenuItem();
        jMenuMantenimientoCliente = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frmPrincipal.setMinimumSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout frmPrincipalLayout = new javax.swing.GroupLayout(frmPrincipal);
        frmPrincipal.setLayout(frmPrincipalLayout);
        frmPrincipalLayout.setHorizontalGroup(
            frmPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        frmPrincipalLayout.setVerticalGroup(
            frmPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuVenta.setText("Ventas");
        jMenuVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVentaActionPerformed(evt);
            }
        });

        jMenuVender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuVender.setText("Vender");
        jMenuVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVenderActionPerformed(evt);
            }
        });
        jMenuVenta.add(jMenuVender);

        jMenuBar1.add(jMenuVenta);

        jMenuMantenimiento.setText("Mantenimiento");
        jMenuMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuMantenimientoVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuMantenimientoVendedor.setText("Vendedor");
        jMenuMantenimientoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMantenimientoVendedorActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuMantenimientoVendedor);

        jMenuMantenimientoProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuMantenimientoProducto.setText("Producto");
        jMenuMantenimientoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMantenimientoProductoActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuMantenimientoProducto);

        jMenuMantenimientoCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuMantenimientoCliente.setText("Cliente");
        jMenuMantenimientoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMantenimientoClienteActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuMantenimientoCliente);

        jMenuBar1.add(jMenuMantenimiento);

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVentaActionPerformed

    }//GEN-LAST:event_jMenuVentaActionPerformed

    private void jMenuVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVenderActionPerformed
        frmVentas fv = new frmVentas();
        CentrarVentana(fv);
        
    }//GEN-LAST:event_jMenuVenderActionPerformed

    private void jMenuMantenimientoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMantenimientoVendedorActionPerformed
        frmVendedor fv =new frmVendedor();
        CentrarVentana(fv);
    }//GEN-LAST:event_jMenuMantenimientoVendedorActionPerformed

    private void jMenuMantenimientoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMantenimientoProductoActionPerformed
        frmProducto fv = new frmProducto();
        CentrarVentana(fv);
    }//GEN-LAST:event_jMenuMantenimientoProductoActionPerformed

    private void jMenuMantenimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMantenimientoClienteActionPerformed
        frmCliente fv = new frmCliente();
        CentrarVentana(fv);      
    }//GEN-LAST:event_jMenuMantenimientoClienteActionPerformed
    void CentrarVentana(JInternalFrame interno){
        frmPrincipal.add(interno);
        Dimension principal = frmPrincipal.getSize();
        Dimension FrameSize = interno.getSize();
        interno.setLocation((principal.width - FrameSize.width)/2, (principal.height- FrameSize.height)/2);
        interno.show();
    }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane frmPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuMantenimiento;
    private javax.swing.JMenuItem jMenuMantenimientoCliente;
    private javax.swing.JMenuItem jMenuMantenimientoProducto;
    private javax.swing.JMenuItem jMenuMantenimientoVendedor;
    private javax.swing.JMenuItem jMenuVender;
    private javax.swing.JMenu jMenuVenta;
    // End of variables declaration//GEN-END:variables
}
